import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules';
import Vue from "@the_tree/esbuild-plugin-vue3";

// mjs文件是更加现代化和规范化的ECMAScript模块，而js文件则是遗留下来的传统JavaScript模块形式。
// mjs文件的优势在于，可以在文件中使用import和export关键字，而不需要使用require和module.exports。但是，由于mjs文件是比较新的规范，所以在使用的时候需要注意一些事项：
// 1. mjs文件必须以.mjs为后缀名，否则会被当做普通的js文件处理。
// 2. mjs文件中可以使用import和export关键字，但是不能使用require和module.exports。
// 3. mjs文件中的顶层this指向undefined，而不是global对象。

const banner =
    `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
process.env.NODE_ENV = 'production';

await esbuild.build({
    banner: {
        js: banner,
    },
    plugins: [
        Vue({ isProd: true })
    ],
    resolveExtensions: ['.vue', '.ts', '.js', '.mjs'],
    entryPoints: ['./src/main.ts'],
    bundle: true,
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/closebrackets',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/comment',
        '@codemirror/fold',
        '@codemirror/gutter',
        '@codemirror/highlight',
        '@codemirror/history',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/matchbrackets',
        '@codemirror/panel',
        '@codemirror/rangeset',
        '@codemirror/rectangular-selection',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/stream-parser',
        '@codemirror/text',
        '@codemirror/tooltip',
        '@codemirror/view',
        ...builtins],
    format: 'cjs',
    watch: !prod,
    target: 'es2016',
    logLevel: "info",
    // 如果是生产环境，设置sourceMap为false，否则开启sourceMap的inline模式，以便在其他环境下调试typescript源码，
    // 不过因为这是一个插件，运行在obsidian中，而不是自己的node中，所以没法被vscode调试，这里的配置就没什么用了
    sourcemap: prod ? false : 'inline',
    minify: prod ? true : false,
    treeShaking: true,
    outfile: 'main.js',
}).catch(() => process.exit(1));

await esbuild.build({
    entryPoints: ["./src/main.css"],
    outfile: "styles.css",
    watch: !prod,
    bundle: true,
    allowOverwrite: true,
    minify: false,
});
